### ISSUE TITLE
金額の表示文字列を3桁ごとに区切る

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#17]
/app/db.py にある `Product.to_price_str(price: int) -> str` メソッドの中身を変更して、文字列を3桁ごとに区切る

---

ライブラリを使って出来そうなことではあるけど、この程度のコードなら自前で実装しよう。

**Comment by koupro0204** [comment]
`/app/db.py `ではなく`app/store/product.py`かと！

**Comment by exflikt** [comment]
> `/app/db.py` ではなく`app/store/product.py` かと！
そういえば、一ヶ月前のコードベースでは前者の位置にありましたが、今のコードベースだと後者の位置に移動しました。
指摘ありがとうございます。
