### ISSUE TITLE
/orders ページで注文を完了したときの番号表示に "#" 記号を付ける

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#27]
/placements ページでは注文番号に "#" 記号 (シャープ、ナンバーサイン、[オクトθープ](https://youtu.be/ul9vyWuT8SU?t=73)) を使ってます。
/orders ページでもこの慣習に合わせましょう。

**Comment by maeyuu8314** [comment]
![スクリーンショット (43)](https://github.com/user-attachments/assets/63101d26-4ff9-4c4f-84b8-01b6192c0459)
このページであってますか？

**Comment by maeyuu8314** [comment]
ありがとうございます！
試してみます。

**Comment by exflikt** [comment]
> ヒント: メッセージは実はPythonの方で生成してます。

**Comment by exflikt** [comment]
Resolved in #32
