### ISSUE TITLE
ページタイトルの順番を前後入れ替える

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#29]
現状だと "murchace - ホーム", "murchace - 新規注文", "murchace - 確定注文" となっているが、ハイフンの前後の単語を入れ替えよう。
ブラウザのタブが多くなったときに、プロジェクト名 (murchace) が見えなくなってもいいが、ページの名前は見えていてほしいので。
テンプレートのheadブロックの内容を編集すればタイトルが変わります。

**Comment by exflikt** [comment]
Resolved in #30

**Comment by seapanda441** [comment]
すいません、具体的にどのファイルのheadブロックの内容を編集すればよろしいでしょうか
