### ISSUE TITLE
Tailwind CSSのソフトウェア再現性が保証されていない

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#42]
開発環境コンテナ Dockerfile https://github.com/tut-cc/murchace/blob/6e1ffb1fb2dd28178d986cfbed7d65f444549e24/.devcontainer/Dockerfile#L12 にある `tailwindcss` バイナリのダウンロードリンクが latest になっていて、バージョン違いで出力CSSファイルの内容が異なる現象が発生するかもしれないです。そこで、バージョンアップグレードを容易にすることも加味して、Tailwind CSS の使用バージョンを見える形で保存し、 Dockerfile でその値を読み取るようにしたいです。`.tailwindcss-version` という名前のファイルを用意するのが良いと思います。

#37 の一環で、 main にマージする前に出力CSSファイルの整合性を確かめるつもりです。なので、本番環境 Dockerfile https://github.com/tut-cc/murchace/blob/6e1ffb1fb2dd28178d986cfbed7d65f444549e24/Dockerfile#L5-L13 で `tailwindcss` バイナリのインストールと `static/styles.min.css` の生成をする必要はないです。

**Comment by dodolia907** [comment]
テストでビルドするときに容易にバージョンを変更できるようにARGを使うというのも浮かんだんですが, `.tailwindcss-version` という名前のファイルを用意するのとどちらのほうが良さそうですかね？
https://docs.docker.jp/engine/reference/builder.html#arg

**Comment by exflikt** [comment]
#43 でバイナリをインストールしてくれる https://github.com/timonweb/pytailwindcss を追加しました。これで、バージョンを環境変数 $TAILWINDCSS_VERSION で指定できるようになります。#43 では justfile に直書きしてますが、`just TAILWINDCSS_VERSION=latest tailwind-watch` で最新版のtailwindcssバイナリを自動でインストールして実行もしてくれます。

バージョン取得は↓のコマンドでいけます：

```sh
$ just -c env | grep TAILWINDCSS_VERSION | cut -d= -f2
v3.4.11
```

このやり方がいいのかは自分でもまだ分からないですけど...

**Comment by exflikt** [comment]
#60 のワークフローで、生成されたCSSファイルをCIテストできるようになったので閉じます。
