### ISSUE TITLE
注文を発行したときにダイアログで注文番号を表示する

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#68]
app/routers/orders.py の `@router.post("/orders/{session_id}")` では

1. セッションの削除
2. 注文の発行
3. `placement_status` の設定
4. 一時注文を変更できないようにするフラグ `order_frozen` の設定

をしてます。
#65 でセッションに注文商品が無い時に確定ボタンを無効して、さらに注文確定の確認ダイアログを追加したので、確認後にダイアログで注文番号を表示するようにしましょう。これで上記リストの3・4番目はなくても動かせるようになるはずです。`placement_status` (状態表示) と `order_frozen` (一時注文変更阻止) の担っていた役割を全部ダイアログに任せることになるので。
ついでに、`/index.html` もしくは確認後のダイアログでしか新しいセッションを生成できないようにしましょう。パス操作関数 `@router.post("/orders/{session_id}/item")`と`@router.delete("/orders/{session_id}")` で `hx_request` が `"true"` であるときに自動的に新しいセッションを生成していますが、この条件分岐は要らなくなります。

---

追記：ダイアログの「確認」は「発行」にしたほうがいいかも？

**Comment by SuzuSys** [comment]
「確定」を押したらダイアログが表示され、「発行」するとダイアログ上で注文番号と「新規」ボタンが表示できるようにします。
<img width="307" alt="image" src="https://github.com/user-attachments/assets/ab881c32-fa4e-4fba-b8fb-c9b25f90459a">

**Comment by koupro0204** [comment]
この番号の取得ってどんな感じにするつもりです？
一端末での注文であれば不整合は発生しない気がしますが、複数端末であれば発生しそうだなと気になりました。

**Comment by SuzuSys** [comment]
> この番号の取得ってどんな感じにするつもりです？ 一端末での注文であれば不整合は発生しない気がしますが、複数端末であれば発生しそうだなと気になりました。

少なくとも現在は、注文番号などのセッション中の状態は全てグローバル変数によって管理されています。

技科大祭では、少なくとも注文は一つの端末によって行われる予定なので不都合は生じませんが、後々のことを考えて、確かに複数の端末による注文でも不都合が生じないようにする必要はあると思います。

どうやらグローバル変数はスレッドセーフではないようです。

https://github.com/fastapi/fastapi/discussions/8119
https://rathoreaparna678.medium.com/sharing-state-in-fastapi-7f86034e8656

**Comment by SuzuSys** [comment]
内部に非同期処理がない関数から async を取り外してもいいかもしれない
https://qiita.com/ikora128/items/35b02714eee7d44f44d6

**Comment by exflikt** [comment]
> この番号の取得ってどんな感じにするつもりです？
> 一端末での注文であれば不整合は発生しない気がしますが、複数端末であれば発生しそうだなと気になりました。

既存の注文セッションへはどのページからも直リンクでアクセスできないようになっています。注文セッションを作ったら注文確定するか放棄の二択しかなく、放棄した場合は直でアクセスできない、という感じです。

ただ、URLバーを編集して直アクセスすると不整合が発生する可能性があるので万全ではないです。あと、放棄しまくるとセッションが貯まりまくってサーバに負荷がかかります。この辺は後々どうにかしたいです。

> どうやらグローバル変数はスレッドセーフではないようです。

Pythonのグローバル変数はMutexだと思ってましたが違うんですね。GILがあるおかげでなんとかしてくれるだろうと勝手に勘違いしてました。FastAPIの `Depends` で色々ゴニョゴニョする必要がありますね。

**Comment by exflikt** [comment]
> （話は変わりますが）内部に非同期処理がない関数から async を取り外してもいいかもしれない

重い同期処理をしている関数は `async` つけてはいけないという話ですね。
同期関数はOSの1スレッド専有[^1] するんですけど、`async` つけたらユーザスペースランタイムのfuture単位で専有する形になります。
中で非同期関数を呼んでいないパス操作関数でも重い同期的処理をしていないのであれば `async` つけほうがパフォーマンス向上するはずです。

[^1]: 厳密には、「スレッド」の定義による。
