### ISSUE TITLE
細かすぎて忘れそうなぐらい微細なUIの調整

### ISSUE THREAD

**Issue by exflikt** [tut-cc/murchace#69]
忘れないために、メモとして残しておきます。

1. - [x] 確定注文ページのヘッダーに位置している「注文」画面へ遷移できるボタンをなくす
    - [x] ボタンに `py-1` を追加する
2. - [x] 確定注文ページのカードで、商品の項目間に薄い線のボーダーを入れる
3. - [ ] クロックが更新したときに要素がずれないようにする

関連: #49, #50

**Comment by exflikt** [comment]
1. @maeyuu8314 
2. @seapanda441 
3. @matsu-pinkdama 
でお願いします

**Comment by maeyuu8314** [comment]
ボタンにpy-1の意味があまりよくわかっていません
上下のパティングを0.25remとありましたが、どのボタンにやるのかがわからないです
教えていただきたいです
